name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'appsettings.json'
      - 'appsettings.*.json'
      - '.gitignore'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/fbki-bot -t ghcr.io/${{ secrets.GHCR_USERNAME }}/fbki-bot:$COMMIT_HASH .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/fbki-bot
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/fbki-bot:$COMMIT_HASH
